version: "3"
services:
  web:
    build: /demo2--cicd
    ports:
      - "8082:8082"
    depends_on:
      - "database"
  solver:
    build: /demo--cicd
    ports:
      - "8081:8091"
    depends_on:
      - "database"
  database:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=webDatabase
