version: '3'

services:
  app1:
    build:
      context: .
      dockerfile: ./demo-cicd/Dockerfile
      args:
        JAR_FILE: ./demo-cicd/target/*.jar
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27011/tmf_test_cicd
    ports:
      - "8080:8081"
    depends_on:
      - mongo
    container_name: demo-cicd

  app2:
    build:
      context: .
      dockerfile: ./demo2-cicd/Dockerfile
      args:
        JAR_FILE: ./demo2-cicd/target/*.jar
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27011/tmf_test_cicd
    ports:
      - "8081:8082"
    depends_on:
      - mongo
    container_name: demo2-cicd

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27011:27017"
    container_name: mongo

volumes:
  mongo_data:

networks:
  app_net:
    driver: bridge
